### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by stumburs** [vacjan321/OthersideFabric#2]
Hi there!

Just asking if an update to 1.21 wouldn't be too much effort to do.
I tried updating it myself, but I'm not too experienced with Java, let alone Minecraft modding, so I ran into issues with the Yarn mapping for moveToWorld, and got a bit stuck.

Thanks!

EDIT:
On 24w21b+build.4 `moveToWorld` has been seemingly removed and replaced with `teleportTo`. Still not 100% sure if switching to `teleportTo` will work, as I have not had been able to test it just yet.

**Comment by luizgabrielsf** [comment]
Hey! Did you try it?
I'm searching for any solution to despawns in my Fabric server, and this is my last hope! Let me know if it's possible to make this work in 1.21, thx!

**Comment by vacjan321** [comment]
Hi

I have just released a new version: https://github.com/vacjan321/OthersideFabric/releases/tag/v1.2
It should be compatible with 1.21+

Please let me know if you have any issues with the mod.

**Comment by luizgabrielsf** [comment]
Thx a lot! I will test!
